name: LeetCode Sync

on:
  schedule:
    - cron: '0 0 * * *' # Adjust this cron schedule as needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Sync LeetCode submissions
      uses: joshcai/leetcode-sync@v1.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        leetcode-session: ${{ secrets.LEETCODE_SESSION }}
        destination-folder: './leetcode-submissions'
        filter-duplicate-secs: 600
